imports:
    - { resource: markeplace/repository.yml  }
    - { resource: markeplace/hook.yml  }
    - { resource: markeplace/provider.yml  }
    - { resource: markeplace/widget.yml  }
    - { resource: markeplace/override.yml  }
    - { resource: markeplace/handler.yml  }
    - { resource: markeplace/command.yml  }
    - { resource: markeplace/grid.yml  }
    - { resource: markeplace/form.yml  }
    - { resource: markeplace/engine.yml  }
parameters: ~

services:
    _defaults:
     public: true

    #    -------------------
    #    override prestashop
    #
    prestashop.hook.dispatcher:
        class: PrestaShop\PrestaShop\Adapter\Hook\HookDispatcher
        arguments:
            - '@request_stack'
        calls:
            - [ addSubscriber, [ "@shoppygo.event.subscriber" ] ]
            - [ addSubscriber, [ "@prestashop.adapter.legacy.hook.subscriber" ] ]
            - [ addSubscriber, [ "@prestashop.adapter.legacy.block.helper.subscriber" ] ]

    shoppygo.core:
        class: ShoppyGo\MarketplaceBundle\Classes\MarketplaceCore
        arguments:
            - '@prestashop.adapter.legacy.context'
            - '@shoppygo.marketplace.repository.seller_repository'
            - '@shoppygo.marketplace.repository.marketplace_seller_repository'
    #
    shoppygo.event.subscriber:
        class: ShoppyGo\MarketplaceBundle\EventSubscriber\ShoppyGoSubscriber
        arguments:
            - !tagged shoppygo.hook
            - '@monolog.logger'

    shoppygo.marketplace.order.split:
      class: ShoppyGo\MarketplaceBundle\Classes\MarketplaceOrderSplit
      arguments:
        - '@shoppygo.marketplace.repository.seller_order_repository'
        - '@shoppygo.marketplace.repository.seller.product'
        - '@monolog.logger'
