services:
  shoppygo.marketplace.setup.command:
    class: ShoppyGo\MarketplaceBundle\Command\SetupMarketplaceCommand
    calls:
      - [setDoctrine, ['@doctrine']]
      - [setTranslator, ['@translator']]
    tags:
      - 'console.command'
  shoppygo.marketplace.setup.database:
    class: ShoppyGo\MarketplaceBundle\Command\SetupMarketplaceDatabaseCommand
    calls:
      - [setDoctrine, ['@doctrine']]
    tags:
      - 'console.command'
  shoppygo.marketplace.seller_orders.command:
    class: ShoppyGo\MarketplaceBundle\Command\SellerSplitOrdersCommand
    calls:
      - [setDoctrine, ['@doctrine']]
      - [setMarketplaceSellerProductRepository, ['@shoppygo.marketplace.repository.seller.product']]
      - [setSplitOrder, ['@shoppygo.marketplace.order.split']]
    tags:
      - 'console.command'
  shoppygo.marketplace.seller_order.command:
    class: ShoppyGo\MarketplaceBundle\Command\SellerSplitSingleOrderCommand
    calls:
      - [setDoctrine, ['@doctrine']]
      - [setMarketplaceSellerProductRepository, ['@shoppygo.marketplace.repository.seller.product']]
      - [setSplitOrder, ['@shoppygo.marketplace.order.split']]
    tags:
      - 'console.command'
