services:
  shoppygo.marketplace.setup.command:
    class: ShoppyGo\MarketplaceBundle\Command\SetupMarketplaceCommand
    calls:
      - [setDoctrine, ['@doctrine']]
    tags:
      - 'console.command'
  shoppygo.marketplace.seller_order.command:
    class: ShoppyGo\MarketplaceBundle\Command\SellerOrderCommand
    calls:
      - [setDoctrine, ['@doctrine']]
      - [setMarketplaceSellerProductRepository, ['@shoppygo.marketplace.repository.seller.product']]
      - [setSplitOrder, ['@shoppygo.marketplace.order.split']]
    tags:
      - 'console.command'
