services:
  shoppygo.marketplace.engine.calculator_engine:
    class: 'ShoppyGo\MarketplaceBundle\Engine\CalculatorEngine'
    public: true

  shoppygo.marketplace.seller_commission_calculator:
    class: 'ShoppyGo\MarketplaceBundle\Engine\MarketplaceCommissionCalculator'
    arguments:
      - '@shoppygo.marketplace.repository.marketplace_seller_repository'
      - '@shoppygo.marketplace.repository.seller_order_repository'
      - '@shoppygo.marketplace.engine.calculator_engine'
    public: true
