services:
  shoppygo_marketplace_seller_choice_type:
    class: ShoppyGo\MarketplaceBundle\Form\Type\SellerChoiceType
    arguments:
      - '@shoppygo.provider.seller.choices'
    tags:
      - { name: form.type }
  shoppygo_marketplace_seller_shipping_configuration_type:
    class: ShoppyGo\MarketplaceBundle\Form\Type\MarketplaceShippingConfigurationType
    arguments:
      - '@shoppygo.core'
      - '@translator'
      - '@prestashop.adapter.data_provider.tax'
    tags:
      - { name: form.type }
