services:
#    bwlab_marketplace_add_seller_handler:
#        class: Bwlab\Marketplace\Domain\Seller\CommandHandler\ReplaceSellerCommandHandler
#        arguments: [ '@doctrine' ]
#        tags:
#            - name: tactician.handler
#              command: 'Bwlab\Marketplace\Domain\Seller\Command\ReplaceSellerCommand'
#
#    bwlab_marketplace_toggle_seller_handler:
#        class: Bwlab\Marketplace\Domain\Seller\CommandHandler\ToggleSellerCommandHandler
#        arguments: [ '@doctrine' ]
#        tags:
#            - name: tactician.handler
#              command: 'Bwlab\Marketplace\Domain\Seller\Command\ToggleSellerCommand'
#
#    bwlab_marketplace_create_seller_product_handler:
#        class: Bwlab\Marketplace\Domain\Product\CommandHandler\CreateSellerProductCommandHandler
#        arguments:
#            - '@doctrine'
#            - '@prestashop.adapter.legacy.context'
#        tags:
#            - name: tactician.handler
#              command: 'Bwlab\Marketplace\Domain\Product\Command\CreateSellerProductCommand'
#
#    bwlab_marketplace_add_category_handler:
#        class: Bwlab\Marketplace\Domain\Seller\CommandHandler\ReplaceSellerCommandHandler
#        arguments: [ '@doctrine' ]
#        tags:
#            - name: tactician.handler
#              command: 'Bwlab\Marketplace\Domain\Seller\Command\ReplaceSellerCommand'
#
    bwlab.marketplace.toggle.category.handler:
        class: ShoppyGo\MarketplaceBundle\Domain\Seller\CommandHandler\ToggleSellerCommandHandler
        arguments: [ '@doctrine' ]
        tags:
            - name: tactician.handler
              command: 'ShoppyGo\MarketplaceBundle\Domain\Seller\Command\ToggleSellerCommand'

    shoppygo.marketplace.create.seller.product.handler:
        class: ShoppyGo\MarketplaceBundle\Domain\Product\CommandHandler\CreateSellerProductCommandHandler
        arguments: [ '@doctrine', '@prestashop.adapter.legacy.context', '@shoppygo.marketplace.repository.marketplace_seller_repository' ]
        tags:
            - name: tactician.handler
              command: 'ShoppyGo\MarketplaceBundle\Domain\Product\Command\CreateSellerProductCommand'
