services:
  ShoppyGo\MarketplaceBundle\Controller\MarketplaceSellerProductController:
        class: ShoppyGo\MarketplaceBundle\Controller\MarketplaceSellerProductController
        decorates: PrestaShopBundle\Controller\Admin\ProductController
        arguments: [ '@ShoppyGo\MarketplaceBundle\Controller\MarketplaceSellerProductController.inner' ]
    #    public: true
#    prestashop.adapter.data_provider.category:
#        class: ShoppyGo\MarketplaceBundle\Provider\SellerCategoryDataProvider
#        arguments:
#            - "@=service('prestashop.adapter.legacy.context')"
#            - '@shoppygo.core'
#            - '@shoppygo.marketplace.repository.category_repository'
  prestashop.adapter.order.query_handler.get_order_for_viewing_handler:
    class: ShoppyGo\MarketplaceBundle\Adapter\Order\QueryHandler\GetOrderForViewingMarketplaceHandler
    arguments:
      - '@translator'
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
      - "@prestashop.core.localization.locale.context_locale"
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@prestashop.adapter.data_provider.customer'
      - '@prestashop.adapter.order.query_handler.get_order_products_for_viewing_handler'
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.address.formatter'
    calls:
      - [setMarketplaceCore,['@shoppygo.core']]
      - [setSellerOrderRepo,['@shoppygo.marketplace.repository.seller_order_repository']]
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Order\Query\GetOrderForViewing
  prestashop.adapter.data_provider.order_state:
    class: ShoppyGo\MarketplaceBundle\Adapter\OrderState\OrderStateDataProvider
    calls:
      - [ setOrderStatusRepository, [ '@shoppygo.marketplace.repository.order_status_repository' ] ]
      - [ setCore, ['@shoppygo.core']]

